export default {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'type-enum': [
      2,
      'always',
      [
        'feat',
        'fix',
        'refactor',
        'perf',
        'test',
        'chore',
        'docs',
        'build',
        'ci',
        'style',
        'revert',
      ],
    ],
    'scope-enum': [
      2,
      'always',
      [
        'api',
        'customer',
        'admin',
        'shop',
        'ui',
        'design-tokens',
        'types',
        'utils',
        'constants',
        'api-contracts',
        'validation',
        'config',
        'auth',
        'logging',
        'e2e',
        'tests',
        'docs',
        'infra',
        'scripts',
        'ci',
        'root',
      ],
    ],
    'subject-case': [2, 'never', ['sentence-case', 'start-case']],
  },
};
