import globals from "globals";
import reactHooks from "eslint-plugin-react-hooks";
import tseslint from "typescript-eslint";

export default tseslint.config(
  {
    ignores: [
      "dist/**",
      ".wrangler/**",
      "node_modules/**",
      "playwright-report/**",
      "test-results/**",
      "coverage/**",
      "prisma/generated/**",
      ".tsbuild/**",
      "e2e/**",
      "eslint.config.js",
      "functions/**",
      "postcss.config.js",
      "public/sw.js",
      "**/__tests__/**",
      "**/*.test.ts",
      "**/*.test.tsx",
      "**/*.spec.ts",
      "**/*.spec.tsx",
    ],
  },
  tseslint.configs.recommended,
  {
    files: ["**/*.{js,mjs,cjs,ts,tsx}"],
    languageOptions: {
      globals: {
        ...globals.browser,
        ...globals.node,
        PagesFunction: "readonly",
      },
      parserOptions: {
        projectService: {
          allowDefaultProject: [
            "scripts/api-dev-server.ts",
            "scripts/backup-database.ts",
            "scripts/cleanup-media.ts",
            "scripts/fix-broken-images.ts",
            "scripts/investigate-relationships.ts",
            "scripts/reset-storage.ts",
            "scripts/restore-database.ts",
            "scripts/rollback-migration.ts",
            "scripts/sync-public-headers.ts",
            "scripts/update-razorpay-secrets.ts",
            "scripts/verify-cloudinary.ts",
            "scripts/verify-database.ts",
            "scripts/reconcile-orphan-users.ts",
            "scripts/cleanup-account.ts",
            "scripts/cleanup-all-supabase-users.ts",
            "scripts/delete-supabase-user.ts",
            "scripts/fix-prisma-fields.mjs",
            "scripts/fix-prisma-names.mjs",
            "scripts/list-profiles.ts",
            "scripts/list-supabase-users.ts",
            "prisma/seed/*.ts",
            "prisma/seed/admin/*.ts",
            "prisma/seed/cms/*.ts",
            "prisma/seed/customers/*.ts",
            "prisma/seed/products/*.ts",
            "prisma/seed/system/*.ts",
            "prisma/seed/utils/*.ts",
            "prisma/seed/marketing/*.ts",
          ],
          maximumDefaultProjectFileMatchCount_THIS_WILL_SLOW_DOWN_LINTING: 100,
        },
        tsconfigRootDir: import.meta.dirname,
      },
    },
    plugins: {
      "react-hooks": reactHooks,
    },
    rules: {
      "react-hooks/rules-of-hooks": "error",
      "react-hooks/exhaustive-deps": "off",
      "no-debugger": "error",
      "no-unreachable": "error",
      "no-constant-condition": ["error", { "checkLoops": false }],
      "no-console": "off",
      "no-unused-vars": "off",
      "@typescript-eslint/no-unused-vars": "off",
      "@typescript-eslint/no-explicit-any": "off",
      "@typescript-eslint/no-floating-promises": "off",
      "@typescript-eslint/consistent-type-imports": ["warn", {
        prefer: "type-imports",
        fixStyle: "inline-type-imports",
      }],
    },
  },
);
