export {
  useCustomerDashboard,
  useCustomerProfile,
  useUpdateProfile,
  useChangePassword,
  useCustomerAddresses,
  useCreateAddress,
  useUpdateAddress,
  useDeleteAddress,
  useCustomerWishlist,
  useAddToWishlist,
  useRemoveFromWishlist,
  useCustomerNotifications,
  useUnreadNotificationCount,
  useMarkNotificationRead,
  useMarkAllNotificationsRead,
  useCustomerSupportTickets,
  useCreateSupportTicket,
  useAddSupportReply,
  useCustomerFAQs,
} from "./hooks/useCustomer";
