/**
 * Order Service
 *
 * Implements the core business logic for order management.
 * This service orchestrates the repository, state machine, and timeline service
 * to provide a complete order management solution.
 *
 * Source: ORDER_MANAGEMENT_ARCHITECTURE.md (binding)
 */

import type { PrismaClient } from '@prisma/client';

import { OrderStatus, CustomerVisibleOrderStatus } from './enums';
import { OrderRepository } from './repository';
import { orderStateMachine } from './state-machine';
import { timelineService } from './timeline';
import type {
  Order,
  OrderSnapshot,
  CheckoutSnapshot,
  TransitionRequest,
  TransitionResponse,
  Timeline,
} from './types';

// ──────────────────────────────────────────────────────────────────────────────
// Order Service Class
// ──────────────────────────────────────────────────────────────────────────────

/**
 * Order Service
 *
 * Provides high-level business operations for order management.
 * All business logic belongs here - never in APIs or UI.
 */
export class OrderService {
  private repository: OrderRepository;

  constructor(prisma: PrismaClient) {
    this.repository = new OrderRepository(prisma);
  }

  /**
   * Create an order from a checkout snapshot.
   * This is the primary entry point for order creation.
   */
  async createFromCheckout(snapshot: CheckoutSnapshot): Promise<Order> {
    // Generate order number: NAB-YYYYMMDD-XXXXXX
    const orderNumber = await this.generateOrderNumber();

    // Map checkout snapshot to order snapshot
    const orderSnapshot: OrderSnapshot = {
      customerId: snapshot.customerId,
      guestToken: snapshot.guestToken,
      customerEmail: snapshot.customerEmail,
      customerPhone: snapshot.customerPhone,
      customerName: snapshot.customerName,
      items: snapshot.items.map((item) => ({
        id: '', // Will be generated by database
        orderId: '', // Will be set by database
        productId: item.productId,
        variantId: item.variantId,
        productName: item.productName,
        sku: item.sku,
        attributes: item.attributes,
        unitPrice: item.unitPrice,
        quantity: item.quantity,
        lineTotal: item.lineTotal,
        imageUrl: item.imageUrl,
        fulfillmentStatus: 'pending',
        refundStatus: 'none',
        returnStatus: 'none',
        refundedQuantity: 0,
        returnedQuantity: 0,
        warehouseId: null,
        reservationId: null,
        metadata: null,
      })),
      amounts: snapshot.amounts,
      shippingAddress: snapshot.shippingAddress,
      billingAddress: snapshot.billingAddress,
      couponCode: snapshot.couponCode,
      source: snapshot.source || 'website',
      metadata: snapshot.metadata,
    };

    // Create order with initial status
    const order = await this.repository.create({
      orderNumber,
      userId: orderSnapshot.customerId,
      guestToken: orderSnapshot.guestToken,
      status: OrderStatus.DRAFT,
      customerVisibleStatus: CustomerVisibleOrderStatus.PENDING,
      paymentStatus: 'pending',
      source: orderSnapshot.source as any,
      items: orderSnapshot.items,
      amounts: orderSnapshot.amounts,
      shippingAddress: orderSnapshot.shippingAddress,
      billingAddress: orderSnapshot.billingAddress,
      couponCode: orderSnapshot.couponCode,
      paymentId: null,
      shipmentId: null,
      shopOwnerId: null,
      cancelledAt: null,
      deliveredAt: null,
      completedAt: null,
      closedAt: null,
      customerEmail: orderSnapshot.customerEmail,
      customerPhone: orderSnapshot.customerPhone,
      customerName: orderSnapshot.customerName,
      notes: null,
      metadata: orderSnapshot.metadata,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    });

    // Create timeline event
    const timelineEvent = timelineService.createOrderCreatedEvent(
      order.id,
      orderNumber,
    );
    await this.repository.createTimelineEvent(timelineEvent);

    return order;
  }

  /**
   * Transition an order to a new state.
   * This validates the transition using the state machine.
   */
  async transitionOrder(
    request: TransitionRequest,
  ): Promise<TransitionResponse> {
    // Fetch current order
    const order = await this.repository.findById(request.orderId);
    if (!order) {
      return {
        success: false,
        result: 'invalid_transition' as any,
        error: 'Order not found',
      };
    }

    // Validate transition using state machine
    const response = await orderStateMachine.transition(order, request);
    if (!response.success) {
      return response;
    }

    // Update order status
    const updatedOrder = await this.repository.update(order.id, {
      status: request.to as any,
      customerVisibleStatus: this.mapToCustomerVisibleStatus(request.to),
    });

    // Create timeline event
    const timelineEvent = timelineService.createStatusTransitionEvent(
      order.id,
      order.status,
      request.to,
      request.reason,
    );
    await this.repository.createTimelineEvent(timelineEvent);

    return {
      success: true,
      order: updatedOrder,
    };
  }

  /**
   * Get order by ID.
   */
  async getOrderById(id: string): Promise<Order | null> {
    return this.repository.findById(id);
  }

  /**
   * Get order by order number.
   */
  async getOrderByNumber(orderNumber: string): Promise<Order | null> {
    return this.repository.findByOrderNumber(orderNumber);
  }

  /**
   * Get orders for a user.
   */
  async getUserOrders(userId: string, options?: any): Promise<Order[]> {
    return this.repository.findByUserId(userId, options);
  }

  /**
   * Get orders with query options.
   */
  async getOrders(options?: any): Promise<Order[]> {
    return this.repository.findMany(options);
  }

  /**
   * Get timeline events for an order
   */
  async getOrderTimeline(orderId: string): Promise<Timeline> {
    const events = await this.repository.getTimelineEvents(orderId);
    return {
      orderId,
      events,
      totalEvents: events.length,
    };
  }

  /**
   * Cancel an order.
   */
  async cancelOrder(
    orderId: string,
    reason: string,
    performedBy: string,
    performedByType: 'customer' | 'admin',
  ): Promise<TransitionResponse> {
    const order = await this.repository.findById(orderId);
    if (!order) {
      return {
        success: false,
        result: 'invalid_transition' as any,
        error: 'Order not found',
      };
    }

    const request: TransitionRequest = {
      orderId,
      to: OrderStatus.CANCELLED,
      reason,
      performedBy,
      performedByType,
    };

    const response = await this.transitionOrder(request);

    if (response.success) {
      // Create cancellation timeline event
      const timelineEvent = timelineService.createOrderCancelledEvent(
        orderId,
        reason,
        performedBy,
        performedByType,
      );
      // TODO: Persist timeline event

      // TODO: Release inventory reservation
      // TODO: Process refund if applicable
    }

    return response;
  }

  /**
   * Request a return for an order.
   */
  async requestReturn(
    orderId: string,
    items: any[],
    reason: string,
    userId: string,
  ): Promise<{ success: boolean; error?: string; returnId?: string }> {
    const order = await this.repository.findById(orderId);
    if (!order) {
      return { success: false, error: 'Order not found' };
    }

    // Check if return is allowed
    if (!orderStateMachine.canReturn(order.status)) {
      return {
        success: false,
        error: 'Return not allowed for this order status',
      };
    }

    // TODO: Create return request in database
    const returnId = crypto.randomUUID();

    // Create timeline event
    const timelineEvent = timelineService.createReturnRequestedEvent(
      orderId,
      returnId,
      reason,
    );
    // TODO: Persist timeline event

    return { success: true, returnId };
  }

  /**
   * Process a refund for an order.
   */
  async processRefund(
    orderId: string,
    amount: string,
    reason: string,
    performedBy: string,
  ): Promise<{ success: boolean; error?: string; refundId?: string }> {
    const order = await this.repository.findById(orderId);
    if (!order) {
      return { success: false, error: 'Order not found' };
    }

    // Check if refund is allowed
    if (!orderStateMachine.canRefund(order.status)) {
      return {
        success: false,
        error: 'Refund not allowed for this order status',
      };
    }

    // TODO: Create refund in database
    const refundId = crypto.randomUUID();

    // Create timeline event
    const timelineEvent = timelineService.createRefundInitiatedEvent(
      orderId,
      refundId,
      amount,
    );
    // TODO: Persist timeline event

    // TODO: Process refund through payment gateway

    // Transition order status if full refund
    const request: TransitionRequest = {
      orderId,
      to: OrderStatus.REFUNDED,
      reason,
      performedBy,
      performedByType: 'admin',
    };

    await this.transitionOrder(request);

    return { success: true, refundId };
  }

  /**
   * Add a note to an order.
   */
  async addNote(
    orderId: string,
    note: string,
    performedBy: string,
    performedByType: 'shop_owner' | 'admin',
  ): Promise<{ success: boolean; error?: string }> {
    const order = await this.repository.findById(orderId);
    if (!order) {
      return { success: false, error: 'Order not found' };
    }

    // Update order notes
    const existingNotes = order.notes || '';
    const updatedNotes = existingNotes ? `${existingNotes}\n\n${note}` : note;

    await this.repository.update(orderId, {
      notes: updatedNotes,
    });

    // Create timeline event
    const timelineEvent = timelineService.createNoteAddedEvent(
      orderId,
      note,
      performedBy,
      performedByType,
    );
    // TODO: Persist timeline event

    return { success: true };
  }

  /**
   * Get order summary statistics.
   */
  async getSummary(options?: any): Promise<any> {
    return this.repository.getSummary(options);
  }

  /**
   * Get dashboard statistics.
   */
  async getDashboardStats(): Promise<any> {
    return this.repository.getDashboardStats();
  }

  /**
   * Generate a unique sequential order number.
   * Format: NAB-YYYYMMDD-XXXXXX (where XXXXXX is a sequential number)
   */
  private async generateOrderNumber(): Promise<string> {
    const now = new Date();
    const datePart = now.toISOString().slice(0, 10).replace(/-/g, '');

    // Get the next sequential number for today
    const sequence = await this.repository.getNextOrderSequence(datePart);
    const sequencePart = sequence.toString().padStart(6, '0');

    return `NAB-${datePart}-${sequencePart}`;
  }
}
