import { CacheService } from "./cache";
interface QueryCacheOptions {
    ttl?: number;
    tags?: string[];
    skipCache?: boolean;
}
export declare class QueryCache {
    private cache;
    constructor(cache: CacheService);
    private serialize;
    private deserialize;
    get<T>(key: string): Promise<T | null>;
    set<T>(key: string, data: T, options?: QueryCacheOptions): Promise<void>;
    invalidate(key: string): Promise<void>;
    invalidateByTag(tag: string): Promise<void>;
    cachedFindMany<T>(key: string, queryFn: () => Promise<T>, options?: QueryCacheOptions): Promise<T>;
    cachedFindFirst<T>(key: string, queryFn: () => Promise<T | null>, options?: QueryCacheOptions): Promise<T | null>;
    cachedFindUnique<T>(key: string, queryFn: () => Promise<T | null>, options?: QueryCacheOptions): Promise<T | null>;
    cachedCount(key: string, queryFn: () => Promise<number>, options?: QueryCacheOptions): Promise<number>;
}
export declare function buildCacheKey(entity: string, params: Record<string, unknown>): string;
export declare function createProductCache(queryCache: QueryCache): {
    getProducts(params?: Record<string, unknown>): Promise<({
        images: {
            id: string;
            type: string | null;
            productId: string;
            variantId: string | null;
            sortOrder: number;
            url: string;
            publicId: string | null;
            altText: string | null;
            isPrimary: boolean;
        }[];
        category: {
            name: string;
            slug: string;
        } | null;
        brand: {
            name: string;
            slug: string;
        } | null;
        variants: {
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            productId: string;
            sku: string;
            size: string;
            color: string;
            colorHex: string | null;
            priceAdjustment: import("@prisma/client/runtime/library").Decimal;
            stock: number;
            reservedStock: number;
            weight: import("@prisma/client/runtime/library").Decimal | null;
            videoUrl: string | null;
            videoPublicId: string | null;
        }[];
    } & {
        name: string;
        id: string;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        currency: string;
        description: string | null;
        slug: string;
        sortOrder: number;
        metaTitle: string | null;
        metaDesc: string | null;
        shortDescription: string | null;
        categoryId: string | null;
        subcategoryId: string | null;
        collectionId: string | null;
        brandId: string | null;
        basePrice: import("@prisma/client/runtime/library").Decimal;
        compareAtPrice: import("@prisma/client/runtime/library").Decimal | null;
        costPrice: import("@prisma/client/runtime/library").Decimal | null;
        salePrice: import("@prisma/client/runtime/library").Decimal | null;
        discountPercent: number | null;
        material: string | null;
        careInstructions: string | null;
        sizeChartUrl: string | null;
        sizeChartPublicId: string | null;
        sizeGuideId: string | null;
        isFeatured: boolean;
        isNew: boolean;
        gender: import("@prisma/client").$Enums.Gender;
        publishedAt: Date | null;
        scheduledPublishAt: Date | null;
        scheduledArchiveAt: Date | null;
    })[]>;
    getProduct(id: string): Promise<({
        images: {
            id: string;
            type: string | null;
            productId: string;
            variantId: string | null;
            sortOrder: number;
            url: string;
            publicId: string | null;
            altText: string | null;
            isPrimary: boolean;
        }[];
        category: {
            name: string;
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            description: string | null;
            slug: string;
            imageUrl: string | null;
            imagePublicId: string | null;
            parentId: string | null;
            sortOrder: number;
            metaTitle: string | null;
            metaDesc: string | null;
        } | null;
        subcategory: {
            name: string;
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            description: string | null;
            slug: string;
            imageUrl: string | null;
            imagePublicId: string | null;
            sortOrder: number;
            categoryId: string;
        } | null;
        collection: {
            name: string;
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            description: string | null;
            slug: string;
            sortOrder: number;
            metaTitle: string | null;
            metaDesc: string | null;
            isFeatured: boolean;
            heroImageUrl: string | null;
            heroImagePublicId: string | null;
            startDate: Date | null;
            endDate: Date | null;
        } | null;
        brand: {
            name: string;
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            description: string | null;
            slug: string;
            sortOrder: number;
            logoUrl: string | null;
            logoPublicId: string | null;
            websiteUrl: string | null;
        } | null;
        sizeGuide: {
            name: string;
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            type: string;
            description: string | null;
            slug: string;
            imageUrl: string | null;
            imagePublicId: string | null;
            categoryId: string | null;
            unit: string;
            measurements: import("@prisma/client/runtime/library").JsonValue;
        } | null;
        attributes: {
            name: string;
            id: string;
            productId: string;
            value: string;
        }[];
        productLabels: ({
            label: {
                name: string;
                id: string;
                createdAt: Date;
                slug: string;
                color: string | null;
            };
        } & {
            productId: string;
            labelId: string;
        })[];
        productTags: ({
            tag: {
                name: string;
                id: string;
                createdAt: Date;
                slug: string;
            };
        } & {
            productId: string;
            tagId: string;
        })[];
        variants: {
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            productId: string;
            sku: string;
            size: string;
            color: string;
            colorHex: string | null;
            priceAdjustment: import("@prisma/client/runtime/library").Decimal;
            stock: number;
            reservedStock: number;
            weight: import("@prisma/client/runtime/library").Decimal | null;
            videoUrl: string | null;
            videoPublicId: string | null;
        }[];
    } & {
        name: string;
        id: string;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        currency: string;
        description: string | null;
        slug: string;
        sortOrder: number;
        metaTitle: string | null;
        metaDesc: string | null;
        shortDescription: string | null;
        categoryId: string | null;
        subcategoryId: string | null;
        collectionId: string | null;
        brandId: string | null;
        basePrice: import("@prisma/client/runtime/library").Decimal;
        compareAtPrice: import("@prisma/client/runtime/library").Decimal | null;
        costPrice: import("@prisma/client/runtime/library").Decimal | null;
        salePrice: import("@prisma/client/runtime/library").Decimal | null;
        discountPercent: number | null;
        material: string | null;
        careInstructions: string | null;
        sizeChartUrl: string | null;
        sizeChartPublicId: string | null;
        sizeGuideId: string | null;
        isFeatured: boolean;
        isNew: boolean;
        gender: import("@prisma/client").$Enums.Gender;
        publishedAt: Date | null;
        scheduledPublishAt: Date | null;
        scheduledArchiveAt: Date | null;
    }) | null>;
    invalidateProduct(id: string): Promise<void>;
};
export declare function createCategoryCache(queryCache: QueryCache): {
    getCategories(): Promise<({
        subcategories: {
            name: string;
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            description: string | null;
            slug: string;
            imageUrl: string | null;
            imagePublicId: string | null;
            sortOrder: number;
            categoryId: string;
        }[];
    } & {
        name: string;
        id: string;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        description: string | null;
        slug: string;
        imageUrl: string | null;
        imagePublicId: string | null;
        parentId: string | null;
        sortOrder: number;
        metaTitle: string | null;
        metaDesc: string | null;
    })[]>;
    getCategory(id: string): Promise<({
        products: ({
            images: {
                id: string;
                type: string | null;
                productId: string;
                variantId: string | null;
                sortOrder: number;
                url: string;
                publicId: string | null;
                altText: string | null;
                isPrimary: boolean;
            }[];
            variants: {
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                productId: string;
                sku: string;
                size: string;
                color: string;
                colorHex: string | null;
                priceAdjustment: import("@prisma/client/runtime/library").Decimal;
                stock: number;
                reservedStock: number;
                weight: import("@prisma/client/runtime/library").Decimal | null;
                videoUrl: string | null;
                videoPublicId: string | null;
            }[];
        } & {
            name: string;
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            currency: string;
            description: string | null;
            slug: string;
            sortOrder: number;
            metaTitle: string | null;
            metaDesc: string | null;
            shortDescription: string | null;
            categoryId: string | null;
            subcategoryId: string | null;
            collectionId: string | null;
            brandId: string | null;
            basePrice: import("@prisma/client/runtime/library").Decimal;
            compareAtPrice: import("@prisma/client/runtime/library").Decimal | null;
            costPrice: import("@prisma/client/runtime/library").Decimal | null;
            salePrice: import("@prisma/client/runtime/library").Decimal | null;
            discountPercent: number | null;
            material: string | null;
            careInstructions: string | null;
            sizeChartUrl: string | null;
            sizeChartPublicId: string | null;
            sizeGuideId: string | null;
            isFeatured: boolean;
            isNew: boolean;
            gender: import("@prisma/client").$Enums.Gender;
            publishedAt: Date | null;
            scheduledPublishAt: Date | null;
            scheduledArchiveAt: Date | null;
        })[];
        subcategories: {
            name: string;
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            description: string | null;
            slug: string;
            imageUrl: string | null;
            imagePublicId: string | null;
            sortOrder: number;
            categoryId: string;
        }[];
    } & {
        name: string;
        id: string;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        description: string | null;
        slug: string;
        imageUrl: string | null;
        imagePublicId: string | null;
        parentId: string | null;
        sortOrder: number;
        metaTitle: string | null;
        metaDesc: string | null;
    }) | null>;
    invalidateCategory(id: string): Promise<void>;
};
export declare function createCollectionCache(queryCache: QueryCache): {
    getCollections(): Promise<({
        products: ({
            images: {
                id: string;
                type: string | null;
                productId: string;
                variantId: string | null;
                sortOrder: number;
                url: string;
                publicId: string | null;
                altText: string | null;
                isPrimary: boolean;
            }[];
            variants: {
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                productId: string;
                sku: string;
                size: string;
                color: string;
                colorHex: string | null;
                priceAdjustment: import("@prisma/client/runtime/library").Decimal;
                stock: number;
                reservedStock: number;
                weight: import("@prisma/client/runtime/library").Decimal | null;
                videoUrl: string | null;
                videoPublicId: string | null;
            }[];
        } & {
            name: string;
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            currency: string;
            description: string | null;
            slug: string;
            sortOrder: number;
            metaTitle: string | null;
            metaDesc: string | null;
            shortDescription: string | null;
            categoryId: string | null;
            subcategoryId: string | null;
            collectionId: string | null;
            brandId: string | null;
            basePrice: import("@prisma/client/runtime/library").Decimal;
            compareAtPrice: import("@prisma/client/runtime/library").Decimal | null;
            costPrice: import("@prisma/client/runtime/library").Decimal | null;
            salePrice: import("@prisma/client/runtime/library").Decimal | null;
            discountPercent: number | null;
            material: string | null;
            careInstructions: string | null;
            sizeChartUrl: string | null;
            sizeChartPublicId: string | null;
            sizeGuideId: string | null;
            isFeatured: boolean;
            isNew: boolean;
            gender: import("@prisma/client").$Enums.Gender;
            publishedAt: Date | null;
            scheduledPublishAt: Date | null;
            scheduledArchiveAt: Date | null;
        })[];
    } & {
        name: string;
        id: string;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        description: string | null;
        slug: string;
        sortOrder: number;
        metaTitle: string | null;
        metaDesc: string | null;
        isFeatured: boolean;
        heroImageUrl: string | null;
        heroImagePublicId: string | null;
        startDate: Date | null;
        endDate: Date | null;
    })[]>;
    getCollection(id: string): Promise<({
        products: ({
            images: {
                id: string;
                type: string | null;
                productId: string;
                variantId: string | null;
                sortOrder: number;
                url: string;
                publicId: string | null;
                altText: string | null;
                isPrimary: boolean;
            }[];
            variants: {
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                productId: string;
                sku: string;
                size: string;
                color: string;
                colorHex: string | null;
                priceAdjustment: import("@prisma/client/runtime/library").Decimal;
                stock: number;
                reservedStock: number;
                weight: import("@prisma/client/runtime/library").Decimal | null;
                videoUrl: string | null;
                videoPublicId: string | null;
            }[];
        } & {
            name: string;
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            currency: string;
            description: string | null;
            slug: string;
            sortOrder: number;
            metaTitle: string | null;
            metaDesc: string | null;
            shortDescription: string | null;
            categoryId: string | null;
            subcategoryId: string | null;
            collectionId: string | null;
            brandId: string | null;
            basePrice: import("@prisma/client/runtime/library").Decimal;
            compareAtPrice: import("@prisma/client/runtime/library").Decimal | null;
            costPrice: import("@prisma/client/runtime/library").Decimal | null;
            salePrice: import("@prisma/client/runtime/library").Decimal | null;
            discountPercent: number | null;
            material: string | null;
            careInstructions: string | null;
            sizeChartUrl: string | null;
            sizeChartPublicId: string | null;
            sizeGuideId: string | null;
            isFeatured: boolean;
            isNew: boolean;
            gender: import("@prisma/client").$Enums.Gender;
            publishedAt: Date | null;
            scheduledPublishAt: Date | null;
            scheduledArchiveAt: Date | null;
        })[];
    } & {
        name: string;
        id: string;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        description: string | null;
        slug: string;
        sortOrder: number;
        metaTitle: string | null;
        metaDesc: string | null;
        isFeatured: boolean;
        heroImageUrl: string | null;
        heroImagePublicId: string | null;
        startDate: Date | null;
        endDate: Date | null;
    }) | null>;
    invalidateCollection(id: string): Promise<void>;
};
export declare function createBrandCache(queryCache: QueryCache): {
    getBrands(): Promise<{
        name: string;
        id: string;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        description: string | null;
        slug: string;
        sortOrder: number;
        logoUrl: string | null;
        logoPublicId: string | null;
        websiteUrl: string | null;
    }[]>;
    getBrand(id: string): Promise<({
        products: ({
            images: {
                id: string;
                type: string | null;
                productId: string;
                variantId: string | null;
                sortOrder: number;
                url: string;
                publicId: string | null;
                altText: string | null;
                isPrimary: boolean;
            }[];
            variants: {
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                productId: string;
                sku: string;
                size: string;
                color: string;
                colorHex: string | null;
                priceAdjustment: import("@prisma/client/runtime/library").Decimal;
                stock: number;
                reservedStock: number;
                weight: import("@prisma/client/runtime/library").Decimal | null;
                videoUrl: string | null;
                videoPublicId: string | null;
            }[];
        } & {
            name: string;
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            currency: string;
            description: string | null;
            slug: string;
            sortOrder: number;
            metaTitle: string | null;
            metaDesc: string | null;
            shortDescription: string | null;
            categoryId: string | null;
            subcategoryId: string | null;
            collectionId: string | null;
            brandId: string | null;
            basePrice: import("@prisma/client/runtime/library").Decimal;
            compareAtPrice: import("@prisma/client/runtime/library").Decimal | null;
            costPrice: import("@prisma/client/runtime/library").Decimal | null;
            salePrice: import("@prisma/client/runtime/library").Decimal | null;
            discountPercent: number | null;
            material: string | null;
            careInstructions: string | null;
            sizeChartUrl: string | null;
            sizeChartPublicId: string | null;
            sizeGuideId: string | null;
            isFeatured: boolean;
            isNew: boolean;
            gender: import("@prisma/client").$Enums.Gender;
            publishedAt: Date | null;
            scheduledPublishAt: Date | null;
            scheduledArchiveAt: Date | null;
        })[];
    } & {
        name: string;
        id: string;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        description: string | null;
        slug: string;
        sortOrder: number;
        logoUrl: string | null;
        logoPublicId: string | null;
        websiteUrl: string | null;
    }) | null>;
    invalidateBrand(id: string): Promise<void>;
};
export {};
