import { ErrorCode } from "./types";
export declare function success<T>(data: T, status?: number): Response;
export declare function created<T>(data: T): Response;
export declare function error(code: ErrorCode, message: string, status?: number, details?: unknown, requestId?: string): Response;
export declare function badRequest(message: string, details?: unknown, requestId?: string): Response;
export declare function unauthorized(message?: string, requestId?: string): Response;
export declare function forbidden(message?: string, requestId?: string): Response;
export declare function notFound(message?: string, requestId?: string): Response;
export declare function conflict(message: string, requestId?: string): Response;
export declare function serverError(_err?: unknown, requestId?: string): Response;
export declare function rateLimitExceeded(message?: string, requestId?: string): Response;
