import { type PrismaClient, Gender } from '@prisma/client';

export async function seedProducts(prisma: PrismaClient) {
  const womenCategory = await prisma.category.findUnique({ where: { slug: 'women' } });
  const menCategory = await prisma.category.findUnique({ where: { slug: 'men' } });
  const accessoriesCategory = await prisma.category.findUnique({ where: { slug: 'accessories' } });
  const footwearCategory = await prisma.category.findUnique({ where: { slug: 'footwear' } });
  const nabomeBrand = await prisma.brand.findUnique({ where: { slug: 'nabome-essentials' } });
  const artisanBrand = await prisma.brand.findUnique({ where: { slug: 'artisan-collective' } });
  const urbanBrand = await prisma.brand.findUnique({ where: { slug: 'urban-studio' } });

  const products = [
    // Women's Products
    {
      name: 'Silk Midi Dress',
      slug: 'silk-midi-dress',
      description: 'Elegant silk midi dress with a flowing silhouette. Perfect for evening occasions and special events. Features a subtle sheen and drapes beautifully.',
      shortDescription: 'Elegant silk midi dress with flowing silhouette',
      categoryId: womenCategory?.id,
      basePrice: 4500,
      compareAtPrice: 5500,
      currency: 'INR',
      material: '100% Silk',
      careInstructions: 'Dry clean only. Do not bleach. Cool iron if needed.',
      isActive: true,
      isFeatured: true,
      isNew: true,
      gender: Gender.FEMALE,
      sortOrder: 1,
      metaTitle: 'Silk Midi Dress | Premium Women\'s Fashion',
      metaDesc: 'Elegant silk midi dress with flowing silhouette. Perfect for evening occasions.',
      brandId: nabomeBrand?.id,
    },
    {
      name: 'Linen Blouse',
      slug: 'linen-blouse',
      description: 'Breathable linen blouse with relaxed fit. Ideal for warm weather and casual elegance. Features mother-of-pearl buttons and subtle texture.',
      shortDescription: 'Breathable linen blouse with relaxed fit',
      categoryId: womenCategory?.id,
      basePrice: 2200,
      compareAtPrice: null,
      currency: 'INR',
      material: '100% Linen',
      careInstructions: 'Machine wash cold. Tumble dry low. Iron while damp.',
      isActive: true,
      isFeatured: true,
      isNew: false,
      gender: Gender.FEMALE,
      sortOrder: 2,
      metaTitle: 'Linen Blouse | Premium Women\'s Tops',
      metaDesc: 'Breathable linen blouse with relaxed fit. Perfect for warm weather.',
      brandId: nabomeBrand?.id,
    },
    {
      name: 'Tailored Wide-Leg Trousers',
      slug: 'tailored-wide-leg-trousers',
      description: 'Sophisticated wide-leg trousers with tailored waistband. Made from premium cotton blend for comfort and structure. Pairs perfectly with our silk blouses.',
      shortDescription: 'Sophisticated wide-leg trousers with tailored waistband',
      categoryId: womenCategory?.id,
      basePrice: 3200,
      compareAtPrice: 3800,
      currency: 'INR',
      material: '98% Cotton, 2% Elastane',
      careInstructions: 'Machine wash cold. Do not bleach. Tumble dry low.',
      isActive: true,
      isFeatured: false,
      isNew: true,
      gender: Gender.FEMALE,
      sortOrder: 3,
      metaTitle: 'Tailored Wide-Leg Trousers | Premium Women\'s Bottoms',
      metaDesc: 'Sophisticated wide-leg trousers with tailored waistband. Premium cotton blend.',
      brandId: nabomeBrand?.id,
    },
    {
      name: 'Cashmere Cardigan',
      slug: 'cashmere-cardigan',
      description: 'Luxurious cashmere cardigan with soft hand feel. Lightweight yet warm, perfect for layering. Features ribbed cuffs and hem.',
      shortDescription: 'Luxurious cashmere cardigan with soft hand feel',
      categoryId: womenCategory?.id,
      basePrice: 6500,
      compareAtPrice: 7500,
      currency: 'INR',
      material: '100% Cashmere',
      careInstructions: 'Dry clean only. Do not bleach. Lay flat to dry.',
      isActive: true,
      isFeatured: true,
      isNew: false,
      gender: Gender.FEMALE,
      sortOrder: 4,
      metaTitle: 'Cashmere Cardigan | Premium Women\'s Knitwear',
      metaDesc: 'Luxurious cashmere cardigan with soft hand feel. Perfect for layering.',
      brandId: artisanBrand?.id,
    },
    {
      name: 'Structured Wool Coat',
      slug: 'structured-wool-coat',
      description: 'Timeless wool coat with structured shoulders and tailored silhouette. Made from premium Italian wool. Features hidden button closure and lined interior.',
      shortDescription: 'Timeless wool coat with structured shoulders',
      categoryId: womenCategory?.id,
      basePrice: 12000,
      compareAtPrice: 14000,
      currency: 'INR',
      material: '100% Wool',
      careInstructions: 'Dry clean only. Store on padded hanger.',
      isActive: true,
      isFeatured: true,
      isNew: false,
      gender: Gender.FEMALE,
      sortOrder: 5,
      metaTitle: 'Structured Wool Coat | Premium Women\'s Outerwear',
      metaDesc: 'Timeless wool coat with structured shoulders. Premium Italian wool.',
      brandId: artisanBrand?.id,
    },
    {
      name: 'Cotton Midi Skirt',
      slug: 'cotton-midi-skirt',
      description: 'Versatile cotton midi skirt with A-line silhouette. Features side pockets and elasticated back waistband. Perfect for everyday wear.',
      shortDescription: 'Versatile cotton midi skirt with A-line silhouette',
      categoryId: womenCategory?.id,
      basePrice: 1800,
      compareAtPrice: null,
      currency: 'INR',
      material: '100% Cotton',
      careInstructions: 'Machine wash cold. Tumble dry low. Iron if needed.',
      isActive: true,
      isFeatured: false,
      isNew: true,
      gender: Gender.FEMALE,
      sortOrder: 6,
      metaTitle: 'Cotton Midi Skirt | Premium Women\'s Bottoms',
      metaDesc: 'Versatile cotton midi skirt with A-line silhouette. Everyday essential.',
      brandId: nabomeBrand?.id,
    },

    // Men's Products
    {
      name: 'Oxford Dress Shirt',
      slug: 'oxford-dress-shirt',
      description: 'Classic Oxford dress shirt with spread collar. Made from premium cotton with subtle texture. Features mother-of-pearl buttons and tailored fit.',
      shortDescription: 'Classic Oxford dress shirt with spread collar',
      categoryId: menCategory?.id,
      basePrice: 2800,
      compareAtPrice: 3200,
      currency: 'INR',
      material: '100% Cotton',
      careInstructions: 'Machine wash cold. Tumble dry low. Iron while damp.',
      isActive: true,
      isFeatured: true,
      isNew: false,
      gender: Gender.MALE,
      sortOrder: 7,
      metaTitle: 'Oxford Dress Shirt | Premium Men\'s Shirts',
      metaDesc: 'Classic Oxford dress shirt with spread collar. Premium cotton.',
      brandId: nabomeBrand?.id,
    },
    {
      name: 'Slim Fit Chinos',
      slug: 'slim-fit-chinos',
      description: 'Modern slim-fit chinos with stretch comfort. Made from premium cotton blend. Features classic front pockets and back welt pockets.',
      shortDescription: 'Modern slim-fit chinos with stretch comfort',
      categoryId: menCategory?.id,
      basePrice: 3500,
      compareAtPrice: null,
      currency: 'INR',
      material: '98% Cotton, 2% Elastane',
      careInstructions: 'Machine wash cold. Tumble dry low. Iron if needed.',
      isActive: true,
      isFeatured: true,
      isNew: true,
      gender: Gender.MALE,
      sortOrder: 8,
      metaTitle: 'Slim Fit Chinos | Premium Men\'s Trousers',
      metaDesc: 'Modern slim-fit chinos with stretch comfort. Premium cotton blend.',
      brandId: nabomeBrand?.id,
    },
    {
      name: 'Merino Wool Sweater',
      slug: 'merino-wool-sweater',
      description: 'Luxurious merino wool sweater with crew neck. Lightweight yet warm, perfect for layering. Features ribbed cuffs and hem.',
      shortDescription: 'Luxurious merino wool sweater with crew neck',
      categoryId: menCategory?.id,
      basePrice: 4800,
      compareAtPrice: 5500,
      currency: 'INR',
      material: '100% Merino Wool',
      careInstructions: 'Hand wash cold. Lay flat to dry. Do not bleach.',
      isActive: true,
      isFeatured: true,
      isNew: false,
      gender: Gender.MALE,
      sortOrder: 9,
      metaTitle: 'Merino Wool Sweater | Premium Men\'s Knitwear',
      metaDesc: 'Luxurious merino wool sweater with crew neck. Lightweight yet warm.',
      brandId: artisanBrand?.id,
    },
    {
      name: 'Bomber Jacket',
      slug: 'bomber-jacket',
      description: 'Contemporary bomber jacket with quilted lining. Made from premium nylon with water-resistant finish. Features ribbed cuffs and hem.',
      shortDescription: 'Contemporary bomber jacket with quilted lining',
      categoryId: menCategory?.id,
      basePrice: 7200,
      compareAtPrice: 8500,
      currency: 'INR',
      material: '100% Nylon',
      careInstructions: 'Spot clean only. Do not machine wash. Professional dry clean recommended.',
      isActive: true,
      isFeatured: true,
      isNew: true,
      gender: Gender.MALE,
      sortOrder: 10,
      metaTitle: 'Bomber Jacket | Premium Men\'s Outerwear',
      metaDesc: 'Contemporary bomber jacket with quilted lining. Water-resistant finish.',
      brandId: urbanBrand?.id,
    },
    {
      name: 'Premium T-Shirt',
      slug: 'premium-t-shirt',
      description: 'Essential premium t-shirt with regular fit. Made from heavyweight cotton for durability and comfort. Features reinforced neckline.',
      shortDescription: 'Essential premium t-shirt with regular fit',
      categoryId: menCategory?.id,
      basePrice: 1200,
      compareAtPrice: null,
      currency: 'INR',
      material: '100% Cotton',
      careInstructions: 'Machine wash cold. Tumble dry low. Do not bleach.',
      isActive: true,
      isFeatured: false,
      isNew: false,
      gender: Gender.MALE,
      sortOrder: 11,
      metaTitle: 'Premium T-Shirt | Essential Men\'s Basics',
      metaDesc: 'Essential premium t-shirt with regular fit. Heavyweight cotton.',
      brandId: nabomeBrand?.id,
    },
    {
      name: 'Tailored Blazer',
      slug: 'tailored-blazer',
      description: 'Sophisticated tailored blazer with notch lapels. Made from premium wool blend with structured shoulders. Features functional button cuffs.',
      shortDescription: 'Sophisticated tailored blazer with notch lapels',
      categoryId: menCategory?.id,
      basePrice: 9500,
      compareAtPrice: 11000,
      currency: 'INR',
      material: '80% Wool, 20% Polyester',
      careInstructions: 'Dry clean only. Store on padded hanger.',
      isActive: true,
      isFeatured: true,
      isNew: false,
      gender: Gender.MALE,
      sortOrder: 12,
      metaTitle: 'Tailored Blazer | Premium Men\'s Suits',
      metaDesc: 'Sophisticated tailored blazer with notch lapels. Premium wool blend.',
      brandId: artisanBrand?.id,
    },

    // Accessories
    {
      name: 'Leather Handbag',
      slug: 'leather-handbag',
      description: 'Elegant leather handbag with structured silhouette. Made from full-grain leather with gold-tone hardware. Features multiple compartments.',
      shortDescription: 'Elegant leather handbag with structured silhouette',
      categoryId: accessoriesCategory?.id,
      basePrice: 8500,
      compareAtPrice: 10000,
      currency: 'INR',
      material: 'Full-Grain Leather',
      careInstructions: 'Wipe with damp cloth. Store in dust bag when not in use.',
      isActive: true,
      isFeatured: true,
      isNew: true,
      gender: Gender.FEMALE,
      sortOrder: 13,
      metaTitle: 'Leather Handbag | Premium Women\'s Accessories',
      metaDesc: 'Elegant leather handbag with structured silhouette. Full-grain leather.',
      brandId: artisanBrand?.id,
    },
    {
      name: 'Silk Scarf',
      slug: 'silk-scarf',
      description: 'Luxurious silk scarf with hand-rolled edges. Features subtle geometric pattern in muted tones. Perfect for adding elegance to any outfit.',
      shortDescription: 'Luxurious silk scarf with hand-rolled edges',
      categoryId: accessoriesCategory?.id,
      basePrice: 1800,
      compareAtPrice: null,
      currency: 'INR',
      material: '100% Silk',
      careInstructions: 'Dry clean only. Do not bleach.',
      isActive: true,
      isFeatured: false,
      isNew: false,
      gender: Gender.UNISEX,
      sortOrder: 14,
      metaTitle: 'Silk Scarf | Premium Unisex Accessories',
      metaDesc: 'Luxurious silk scarf with hand-rolled edges. Subtle geometric pattern.',
      brandId: artisanBrand?.id,
    },
    {
      name: 'Leather Belt',
      slug: 'leather-belt',
      description: 'Classic leather belt with brushed metal buckle. Made from premium leather with natural grain. Features adjustable length.',
      shortDescription: 'Classic leather belt with brushed metal buckle',
      categoryId: accessoriesCategory?.id,
      basePrice: 1500,
      compareAtPrice: null,
      currency: 'INR',
      material: 'Full-Grain Leather',
      careInstructions: 'Wipe with damp cloth. Avoid excessive moisture.',
      isActive: true,
      isFeatured: false,
      isNew: false,
      gender: Gender.UNISEX,
      sortOrder: 15,
      metaTitle: 'Leather Belt | Premium Unisex Accessories',
      metaDesc: 'Classic leather belt with brushed metal buckle. Premium leather.',
      brandId: nabomeBrand?.id,
    },

    // Footwear
    {
      name: 'Leather Sneakers',
      slug: 'leather-sneakers',
      description: 'Premium leather sneakers with cushioned sole. Made from full-grain leather with breathable lining. Features lace-up closure.',
      shortDescription: 'Premium leather sneakers with cushioned sole',
      categoryId: footwearCategory?.id,
      basePrice: 5500,
      compareAtPrice: 6500,
      currency: 'INR',
      material: 'Full-Grain Leather, Rubber Sole',
      careInstructions: 'Wipe with damp cloth. Air dry. Avoid direct heat.',
      isActive: true,
      isFeatured: true,
      isNew: true,
      gender: Gender.UNISEX,
      sortOrder: 16,
      metaTitle: 'Leather Sneakers | Premium Unisex Footwear',
      metaDesc: 'Premium leather sneakers with cushioned sole. Full-grain leather.',
      brandId: urbanBrand?.id,
    },
    {
      name: 'Chelsea Boots',
      slug: 'chelsea-boots',
      description: 'Classic Chelsea boots with elastic side panels. Made from premium leather with durable sole. Features pull tab for easy wear.',
      shortDescription: 'Classic Chelsea boots with elastic side panels',
      categoryId: footwearCategory?.id,
      basePrice: 6800,
      compareAtPrice: 7800,
      currency: 'INR',
      material: 'Full-Grain Leather, Rubber Sole',
      careInstructions: 'Wipe with damp cloth. Use leather conditioner regularly.',
      isActive: true,
      isFeatured: true,
      isNew: false,
      gender: Gender.UNISEX,
      sortOrder: 17,
      metaTitle: 'Chelsea Boots | Premium Unisex Footwear',
      metaDesc: 'Classic Chelsea boots with elastic side panels. Premium leather.',
      brandId: artisanBrand?.id,
    },
    {
      name: 'Canvas Sneakers',
      slug: 'canvas-sneakers',
      description: 'Casual canvas sneakers with vulcanized sole. Made from durable canvas with comfortable insole. Features classic lace-up design.',
      shortDescription: 'Casual canvas sneakers with vulcanized sole',
      categoryId: footwearCategory?.id,
      basePrice: 2200,
      compareAtPrice: null,
      currency: 'INR',
      material: 'Canvas, Rubber Sole',
      careInstructions: 'Machine wash cold. Air dry. Do not bleach.',
      isActive: true,
      isFeatured: false,
      isNew: false,
      gender: Gender.UNISEX,
      sortOrder: 18,
      metaTitle: 'Canvas Sneakers | Casual Unisex Footwear',
      metaDesc: 'Casual canvas sneakers with vulcanized sole. Durable canvas.',
      brandId: urbanBrand?.id,
    },
  ];

  for (const product of products) {
    const created = await prisma.product.upsert({
      where: { slug: product.slug },
      update: product,
      create: product,
    });

    // Add variants for each product
    await seedProductVariants(prisma, created.id, product.name);
    await seedProductImages(prisma, created.id, product.slug);
  }
}

async function seedProductVariants(prisma: PrismaClient, productId: string, productName: string) {
  const variantConfigs: Record<string, { sizes: string[]; colors: string[] }> = {
    'silk-midi-dress': {
      sizes: ['XS', 'S', 'M', 'L', 'XL'],
      colors: ['Black', 'Navy', 'Emerald', 'Burgundy'],
    },
    'linen-blouse': {
      sizes: ['XS', 'S', 'M', 'L', 'XL'],
      colors: ['White', 'Beige', 'Light Blue', 'Pink'],
    },
    'tailored-wide-leg-trousers': {
      sizes: ['XS', 'S', 'M', 'L', 'XL'],
      colors: ['Black', 'Navy', 'Charcoal', 'Khaki'],
    },
    'cashmere-cardigan': {
      sizes: ['XS', 'S', 'M', 'L', 'XL'],
      colors: ['Cream', 'Grey', 'Navy', 'Oatmeal'],
    },
    'structured-wool-coat': {
      sizes: ['XS', 'S', 'M', 'L', 'XL'],
      colors: ['Black', 'Camel', 'Navy', 'Grey'],
    },
    'cotton-midi-skirt': {
      sizes: ['XS', 'S', 'M', 'L', 'XL'],
      colors: ['Black', 'White', 'Navy', 'Olive'],
    },
    'oxford-dress-shirt': {
      sizes: ['S', 'M', 'L', 'XL', 'XXL'],
      colors: ['White', 'Light Blue', 'Pink', 'Lavender'],
    },
    'slim-fit-chinos': {
      sizes: ['28', '30', '32', '34', '36'],
      colors: ['Khaki', 'Navy', 'Black', 'Olive'],
    },
    'merino-wool-sweater': {
      sizes: ['S', 'M', 'L', 'XL', 'XXL'],
      colors: ['Navy', 'Charcoal', 'Cream', 'Forest Green'],
    },
    'bomber-jacket': {
      sizes: ['S', 'M', 'L', 'XL', 'XXL'],
      colors: ['Black', 'Navy', 'Olive', 'Burgundy'],
    },
    'premium-t-shirt': {
      sizes: ['S', 'M', 'L', 'XL', 'XXL'],
      colors: ['White', 'Black', 'Grey', 'Navy'],
    },
    'tailored-blazer': {
      sizes: ['S', 'M', 'L', 'XL', 'XXL'],
      colors: ['Navy', 'Charcoal', 'Black'],
    },
    'leather-handbag': {
      sizes: ['Small', 'Medium', 'Large'],
      colors: ['Black', 'Tan', 'Burgundy', 'Navy'],
    },
    'silk-scarf': {
      sizes: ['One Size'],
      colors: ['Multi', 'Navy/White', 'Burgundy/Gold', 'Grey/Silver'],
    },
    'leather-belt': {
      sizes: ['32', '34', '36', '38', '40'],
      colors: ['Black', 'Brown', 'Tan'],
    },
    'leather-sneakers': {
      sizes: ['6', '7', '8', '9', '10', '11'],
      colors: ['White', 'Black', 'Tan', 'Navy'],
    },
    'chelsea-boots': {
      sizes: ['6', '7', '8', '9', '10', '11'],
      colors: ['Black', 'Brown', 'Tan'],
    },
    'canvas-sneakers': {
      sizes: ['6', '7', '8', '9', '10', '11'],
      colors: ['White', 'Black', 'Navy', 'Red'],
    },
  };

  const config = variantConfigs[productName.split(' ').join('-').toLowerCase()];
  if (!config) return;

  let stock = 50;
  for (const color of config.colors) {
    for (const size of config.sizes) {
      const sku = `${productName.substring(0, 3).toUpperCase()}-${size}-${color.substring(0, 3).toUpperCase()}-${Math.floor(Math.random() * 1000)}`;
      await prisma.productVariant.create({
        data: {
          productId,
          sku,
          size,
          color,
          stock,
          isActive: true,
        },
      });
      stock = Math.max(10, stock - 5); // Vary stock levels
    }
  }
}

async function seedProductImages(prisma: PrismaClient, productId: string, productSlug: string) {
  const images = [
    {
      url: `https://images.unsplash.com/photo-${getUnsplashId(productSlug)}?w=800&q=80`,
      altText: `${productSlug.replace(/-/g, ' ')} main image`,
      sortOrder: 0,
      isPrimary: true,
    },
    {
      url: `https://images.unsplash.com/photo-${getUnsplashId(productSlug)}-2?w=800&q=80`,
      altText: `${productSlug.replace(/-/g, ' ')} detail view`,
      sortOrder: 1,
      isPrimary: false,
    },
    {
      url: `https://images.unsplash.com/photo-${getUnsplashId(productSlug)}-3?w=800&q=80`,
      altText: `${productSlug.replace(/-/g, ' ')} lifestyle shot`,
      sortOrder: 2,
      isPrimary: false,
    },
  ];

  for (const image of images) {
    await prisma.productImage.create({
      data: {
        productId,
        ...image,
      },
    });
  }
}

function getUnsplashId(slug: string): string {
  const ids: Record<string, string> = {
    'silk-midi-dress': '1515372039744-b287c3f9f4e6',
    'linen-blouse': '1596755094514-f87e34085b2c',
    'tailored-wide-leg-trousers': '1594933837882-5b9e70e6d0f2',
    'cashmere-cardigan': '1434389677669-e08b4cac3105',
    'structured-wool-coat': '1539533018447-63ddce2d1e9e',
    'cotton-midi-skirt': '1583496636141-24a848164c85',
    'oxford-dress-shirt': '1602810368420-4fbb99cc9653',
    'slim-fit-chinos': '1624328185721-68ab8a9a9f6c',
    'merino-wool-sweater': '1576566588028-4147f3842f27',
    'bomber-jacket': '1591047139829-d91aecb6caea',
    'premium-t-shirt': '1521572163470-ee6b2620c5d0',
    'tailored-blazer': '1507003211169-0a1dd7228f2d',
    'leather-handbag': '1584917869449-79a3c9a80c21',
    'silk-scarf': '1520172884726-9b1b3b5b5b5b',
    'leather-belt': '1553062407-98eeb64c6a62',
    'leather-sneakers': '1549298916-b41d501d3772',
    'chelsea-boots': '1632420953734-0223d3d1a6c6',
    'canvas-sneakers': '1549298916-b41d501d3772',
  };
  return ids[slug] || '1515372039744-b287c3f9f4e6';
}
